# Generated by Django 5.0.7 on 2024-09-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
