# Generated by Django 5.0.7 on 2024-09-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0002_design_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='design',
            name='layout_data',
            field=models.JSONField(default=dict),
        ),
    ]
